# Generated by Django 5.1.4 on 2024-12-11 18:24

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Robot',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serial', models.CharField(max_length=5)),
                ('model', models.CharField(max_length=2)),
                ('version', models.CharField(max_length=2)),
                ('created', models.DateTimeField()),
            ],
            options={
                'verbose_name': 'робот',
                'verbose_name_plural': 'Роботы',
                'ordering': ('serial',),
                'default_related_name': 'robots',
                'constraints': [models.UniqueConstraint(fields=('model', 'version'), name='unique_model_version')],
            },
        ),
        migrations.CreateModel(
            name='ProductionLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('production_date', models.DateField(default=django.utils.timezone.now, verbose_name='Дата')),
                ('quantity', models.PositiveIntegerField(verbose_name='Количество')),
                ('robot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='robots.robot', verbose_name='Робот')),
            ],
            options={
                'verbose_name': 'производство',
                'verbose_name_plural': 'Журнал производства',
                'ordering': ('robot',),
                'default_related_name': 'productionlog',
            },
        ),
    ]
