# Generated by Django 5.1.4 on 2024-12-11 15:12

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('robots', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductionLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('production_date', models.DateField(default=django.utils.timezone.now, verbose_name='Дата')),
                ('quantity', models.PositiveIntegerField(verbose_name='Количество')),
            ],
            options={
                'verbose_name': 'производство',
                'verbose_name_plural': 'Журнал производства',
                'ordering': ('robot',),
            },
        ),
        migrations.AlterModelOptions(
            name='robot',
            options={'ordering': ('serial',), 'verbose_name': 'робот', 'verbose_name_plural': 'Роботы'},
        ),
        migrations.AddConstraint(
            model_name='robot',
            constraint=models.UniqueConstraint(fields=('model', 'version'), name='unique_model_version'),
        ),
        migrations.AddField(
            model_name='productionlog',
            name='robot',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='production_logs', to='robots.robot', verbose_name='Робот'),
        ),
    ]
